-- MySQL Script generated by MySQL Workbench
-- 01/28/17 16:28:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema heros_sin_capa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `heros_sin_capa` ;

-- -----------------------------------------------------
-- Schema heros_sin_capa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `heros_sin_capa` DEFAULT CHARACTER SET utf8 ;
USE `heros_sin_capa` ;

-- -----------------------------------------------------
-- Table `heros_sin_capa`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `heros_sin_capa`.`users` ;

CREATE TABLE IF NOT EXISTS `heros_sin_capa`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `lastname` VARCHAR(80) NOT NULL,
  `alias` VARCHAR(120) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `password` VARCHAR(120) NOT NULL,
  `token` VARCHAR(150) NULL,
  `tempToken` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heros_sin_capa`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `heros_sin_capa`.`posts` ;

CREATE TABLE IF NOT EXISTS `heros_sin_capa`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `body` TEXT NOT NULL,
  `image` TEXT NOT NULL,
  `tags` TEXT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_post_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_post_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `heros_sin_capa`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heros_sin_capa`.`post_likes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `heros_sin_capa`.`post_likes` ;

CREATE TABLE IF NOT EXISTS `heros_sin_capa`.`post_likes` (
  `id` INT NOT NULL,
  `post_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_likes_post1_idx` (`post_id` ASC),
  CONSTRAINT `fk_post_likes_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `heros_sin_capa`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heros_sin_capa`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `heros_sin_capa`.`comments` ;

CREATE TABLE IF NOT EXISTS `heros_sin_capa`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `posts_id` INT NOT NULL,
  `comment` TEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT NOW(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`, `posts_id`),
  CONSTRAINT `fk_comments_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `heros_sin_capa`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heros_sin_capa`.`rankeds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `heros_sin_capa`.`rankeds` ;

CREATE TABLE IF NOT EXISTS `heros_sin_capa`.`rankeds` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rank` VARCHAR(45) NOT NULL,
  `passing_score` INT NOT NULL DEFAULT 0,
  `active` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
